#!/usr/bin/env python3
"""Convert the Beamer deck's areas/ into the book's chapters/.

The deck macros are regular enough to convert mechanically:

    \\ExerciseSlide[badge]{stars}{time}{problem}
    \\AnswerSlide[badge]{answer}{hint}

become one frame each, with the ANSWER MOVED FORWARD into the frame after the
exercise it answers -- which is the whole difference between a slide deck and a
Stroud book. A deck can put an answer on its own slide because the reader
cannot see it until they advance; a book cannot, so the answer opens the next
frame and the reader covers the page below the rule instead.

So N exercises become N+1 frames: frames 1..N carry exercise i preceded by the
answer to exercise i-1, and frame N+1 carries the last answer alone.

WHY A SCRIPT AND NOT A HAND EDIT. 38 exercises is small enough to retype and
exactly large enough to retype WRONG -- and the frame design is still settling,
so this has to be re-runnable. It is deliberately NOT a general LaTeX parser:
it matches braces and brackets and copies everything between them verbatim,
which is all this job needs and is the part that can be got right.

    tools/convert_deck.py                 # write book/chapters/
    tools/convert_deck.py --check         # fail if the tree is stale

Diacritics are copied EXACTLY as found. The deck mixes UTF-8 (`Kolejność`) with
TeX escapes (`Mno\\. zenie`, `pu\\l{}apka`); both reach the same glyph under
inputenc and normalising one into the other would be a silent edit to 38
exercises nobody asked for.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AREAS = ROOT / "areas"
CHAPTERS = ROOT / "book" / "chapters"

# Title and one-line topical intro per area. These are the only editorial
# strings in this script: everything else is copied from the deck. The intros
# name what the area covers and deliberately do NOT repeat the how-to-work-it
# instruction -- that is in the front matter, said once, where an instruction
# repeated five times would stop being read.
AREA_META = {
    "1-arytmetyka-podstawy": (
        "Arytmetyka: Podstawy",
        "Dodawanie, odejmowanie, mnożenie i dzielenie — od liczb dwucyfrowych "
        "po czterocyfrowe."),
    "2-kolejnosc-dzialan": (
        "Kolejność Działań",
        "Nawiasy, priorytety i potęgi — czyli w jakiej kolejności liczy się to, "
        "co widzisz."),
    "3-zagadki-logiczne": (
        "Zagadki Logiczne",
        "Sylogizmy, pułapki słowne i dedukcja. Tu liczy się to, co przeczytasz, "
        "nie to, co policzysz."),
    "4-ciagi-i-wzorce": (
        "Ciągi i Wzorce",
        "Ciągi arytmetyczne, geometryczne, Fibonacciego i literowe — znajdź "
        "regułę, potem następny wyraz."),
    "5-mieszane-wyzwania": (
        "Mieszane Wyzwania",
        "Prędkość, procenty, geometria, finanse i praca — zadania z życia, "
        "liczone w pamięci."),
}

HEADER = """\
% ======================================================
%  Rozdział — {title}
%
%  GENERATED by tools/convert_deck.py from areas/{stem}.tex.
%  Edit the deck source and re-run, or convert this chapter to hand-maintained
%  and delete it from the script's AREA_META -- but do not edit both.
%
%  The `% -- NN --` comments are the deck's own global exercise numbers, kept
%  so a reader of either source can find the same exercise in the other. The
%  book itself numbers frames per chapter: within a chapter, frame N is
%  exercise N, because every frame carries exactly one exercise except the last.
% ======================================================

\\chapter{{{title}}}

{intro}
"""


class ParseError(Exception):
    pass


def read_group(s: str, i: int, open_c: str = "{", close_c: str = "}") -> tuple[str, int]:
    """Read a balanced group starting at s[i] == open_c. Returns (body, next_i)."""
    if i >= len(s) or s[i] != open_c:
        raise ParseError(f"expected {open_c!r} at offset {i}: {s[i:i+40]!r}")
    depth, start = 0, i
    while i < len(s):
        c = s[i]
        if c == "\\":            # an escaped brace is not a delimiter
            i += 2
            continue
        if c == open_c:
            depth += 1
        elif c == close_c:
            depth -= 1
            if depth == 0:
                return s[start + 1:i], i + 1
        i += 1
    raise ParseError(f"unbalanced {open_c!r} from offset {start}")


def skip_ws(s: str, i: int) -> int:
    """Skip whitespace and comment-to-end-of-line, as TeX would between args."""
    while i < len(s):
        if s[i] in " \t\r\n":
            i += 1
        elif s[i] == "%":
            j = s.find("\n", i)
            i = len(s) if j < 0 else j + 1
        else:
            break
    return i


def parse_calls(src: str) -> list[dict]:
    """Every \\ExerciseSlide / \\AnswerSlide in source order."""
    out = []
    for m in re.finditer(r"\\(ExerciseSlide|AnswerSlide)", src):
        name = m.group(1)
        i = skip_ws(src, m.end())
        badge = None
        if i < len(src) and src[i] == "[":
            badge, i = read_group(src, i, "[", "]")
            i = skip_ws(src, i)
        n_args = 3 if name == "ExerciseSlide" else 2
        args = []
        for _ in range(n_args):
            body, i = read_group(src, i)
            args.append(body)
            i = skip_ws(src, i)
        # The `% -- NN --` comment that introduces this exercise, if present.
        before = src[:m.start()]
        num = None
        nm = list(re.finditer(r"%\s*--\s*(\d+)\s*--", before))
        if nm:
            num = nm[-1].group(1)
        out.append({"kind": name, "badge": badge, "args": args, "num": num})
    return out


def reflow(body: str) -> str:
    """Tidy a copied argument for the book source without changing its tokens."""
    body = body.strip()
    if "\n" not in body:
        return body
    lines = [ln.strip() for ln in body.splitlines()]
    lines = [ln for ln in lines if ln]
    return "\n      ".join(lines)


def render(stem: str) -> str:
    title, intro = AREA_META[stem]
    calls = parse_calls((AREAS / f"{stem}.tex").read_text(encoding="utf8"))

    ex = [c for c in calls if c["kind"] == "ExerciseSlide"]
    an = [c for c in calls if c["kind"] == "AnswerSlide"]
    if len(ex) != len(an):
        raise ParseError(f"{stem}: {len(ex)} exercises but {len(an)} answers")

    parts = [HEADER.format(title=title, stem=stem, intro=intro)]
    for idx, e in enumerate(ex):
        prev = an[idx - 1] if idx > 0 else None
        parts.append(f"% -- {e['num']} --")
        parts.append("\\begin{fr}")
        if prev is not None:
            parts.append(
                f"  \\ans{{{reflow(prev['args'][0])}}}{{{reflow(prev['args'][1])}}}")
        badge = f"[{e['badge']}]" if e["badge"] else ""
        parts.append(
            f"  \\exercise{badge}{{{e['args'][0].strip()}}}"
            f"{{{e['args'][1].strip()}}}{{{reflow(e['args'][2])}}}")
        parts.append("\\end{fr}")
        parts.append("")

    last = an[-1]
    parts.append("% The chapter's last frame carries the last answer alone.")
    parts.append("\\begin{fr}")
    parts.append(
        f"  \\ans{{{reflow(last['args'][0])}}}{{{reflow(last['args'][1])}}}")
    parts.append("\\end{fr}")
    parts.append("")
    return "\n".join(parts)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="exit non-zero if any chapter is stale")
    a = p.parse_args()

    CHAPTERS.mkdir(parents=True, exist_ok=True)
    stale = []
    for stem in AREA_META:
        text = render(stem)
        dest = CHAPTERS / f"{stem}.tex"
        current = dest.read_text(encoding="utf8") if dest.exists() else None
        if current == text:
            print(f"  ok      {dest.relative_to(ROOT)}")
            continue
        if a.check:
            stale.append(dest.relative_to(ROOT))
            print(f"  STALE   {dest.relative_to(ROOT)}")
        else:
            dest.write_text(text, encoding="utf8")
            print(f"  written {dest.relative_to(ROOT)}")
    if stale:
        print(f"\n{len(stale)} chapter(s) do not match areas/. "
              f"Run tools/convert_deck.py.")
        return 1
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ParseError as e:
        print(f"convert_deck: {e}", file=sys.stderr)
        sys.exit(2)
