#!/usr/bin/env python3
"""Generate the book's drill sets.

WHY GENERATED. This book is scored on how many exercises you get through and
how fast, so it needs thousands of them, and thousands of hand-written sums is
both a waste of a person and a place for arithmetic slips to hide. Everything
here is produced and its answer computed by the same three lines, so a printed
answer cannot disagree with its printed question.

DETERMINISTIC. Every set seeds its own Random with a fixed integer, so the book
is byte-identical on every machine and every run. A drill book whose pages
change under you cannot be re-run to compare times, which is the one thing this
book is for.

    tools/gen_sets.py            # write book/sets/generated/
    tools/gen_sets.py --check    # fail if the tree is stale

Hand-written sets -- logic, sequences, tricks -- live in book/sets/ and are not
touched by this script. Those cannot be generated: a word trap is a joke, and a
joke has an author.
"""
from __future__ import annotations

import argparse
import random
import sys
from collections import Counter
from fractions import Fraction
from math import gcd
from pathlib import Path
from typing import Callable, NamedTuple

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "book" / "sets" / "generated"

# The set length, in one place. It is a property of the FORMAT, not of any one
# set: a reader who has timed set 3 against set 11 is comparing two numbers that
# only mean something if the sets are the same length. Mixed sets divide it with
# split() rather than naming their own counts, so changing this one integer
# moves every set together and none of them drifts out of step.
N = 40

HEADER = """\
% ======================================================
%  GENERATED by tools/gen_sets.py -- do not edit.
%  Seed {seed}; regenerate with `make sets`.
% ======================================================

\\begin{{zestaw}}{opt}{{{title}}}{{{stars}}}{{{target}}}{{{cols}}}
{body}\\end{{zestaw}}
"""


def fmt(n: int) -> str:
    """Polish thousands separator: a thin space, never a comma."""
    s = f"{n:,}".replace(",", r"\,")
    return s


def sgn(n: int) -> str:
    """A negative ANSWER, set in maths so the sign is a minus and not a hyphen.
    The appendix is text mode, where `-12` prints an en-rule the reader has to
    decide about; `$-12$` cannot be misread."""
    return f"${n}$" if n < 0 else fmt(n)


def dec(tenths: int) -> str:
    """Tenths as a decimal for MATH mode. `{,}` because a bare comma in math is
    punctuation and TeX puts a space after it -- `1,5` would set as `1, 5`."""
    return f"{tenths // 10}{{,}}{tenths % 10}"


def dect(tenths: int) -> str:
    """The same number for TEXT mode, where a comma is just a comma. The answer
    appendix is text, so the two forms are not interchangeable."""
    return f"{tenths // 10},{tenths % 10}"


def target(secs: float) -> str:
    """The head's target time, DERIVED rather than chosen: seconds per exercise
    times N. A target typed in by hand is a number that stops being true the
    day N moves, and every set would have to be re-guessed one at a time. This
    reproduces all twenty-five of the original targets exactly."""
    total = round(secs * N)
    return f"{total // 60}:{total % 60:02d}"


def split(n: int, k: int) -> list[int]:
    """k counts summing to n, so a mixed set is exactly N long whatever N is."""
    base, rest = divmod(n, k)
    return [base + (1 if i < rest else 0) for i in range(k)]


def distinct(n, draw, seen=None):
    """n exercises, no two of them the same.

    Every builder below draws at random, and a set is now long enough that by
    the birthday problem it repeats almost every time: forty draws from the
    sixty-four multiplication-table pairs collide on about nine of them. A
    repeat inside one timed set reads as a printing error, and it measures
    nothing the first copy did not already measure.

    The attempt bound is what makes a builder whose space is smaller than n
    fail here, loudly, instead of spinning forever in a build that never ends.
    """
    seen = set() if seen is None else seen
    out, tries = [], 0
    while len(out) < n:
        tries += 1
        if tries > 200 * n:
            raise SystemExit(
                f"gen_sets: {draw.__name__} cannot produce {n} distinct "
                f"exercises -- widen its range or shorten the set")
        q, ans = draw()
        if q in seen:
            continue
        seen.add(q)
        out.append((q, ans))
    return out


# ------------------------------------------------------------------
#  Builders. Each DRAWS ONE exercise and computes its answer from the same
#  values it printed -- there is no second path a typo could take. distinct()
#  above turns a draw into a set.
#
#  NOTE ON NOTATION. Nothing here emits \sqrt or \frac. Both are taller than the
#  \strut that sets the row pitch in \z, so a set built from them breathes at a
#  different rate than every other set, and a reader running down a column with
#  a pencil feels it. Where the operation needs saying, it is said in words.
#
#  NOTE ON DIACRITICS. New exercise text is written in UTF-8, which is what the
#  titles have always used and what inputenc reads. The TeX escapes in
#  podwajanie() are transcribed from the archived deck and are left as found:
#  normalising them would be a silent edit to text nobody asked to change.
# ------------------------------------------------------------------

def dodawanie(r, lo, hi):
    a, b = r.randint(lo, hi), r.randint(lo, hi)
    return f"${fmt(a)} + {fmt(b)}$", fmt(a + b)


def odejmowanie(r, lo, hi):
    a, b = r.randint(lo, hi), r.randint(lo, hi)
    if b > a:
        a, b = b, a
    return f"${fmt(a)} - {fmt(b)}$", fmt(a - b)


def mnozenie(r, alo, ahi, blo, bhi):
    a, b = r.randint(alo, ahi), r.randint(blo, bhi)
    return rf"${fmt(a)} \times {fmt(b)}$", fmt(a * b)


def dzielenie(r, blo, bhi, qlo, qhi):
    """Built from the quotient outwards, so every division comes out exact."""
    b, q = r.randint(blo, bhi), r.randint(qlo, qhi)
    return rf"${fmt(b * q)} \div {fmt(b)}$", fmt(q)


def trzy_skladniki(r):
    a, b, c = r.randint(11, 79), r.randint(11, 79), r.randint(11, 79)
    return f"${a} + {b} + {c}$", fmt(a + b + c)


def cztery_skladniki(r):
    """Four small addends. The skill is holding a running total while the next
    number arrives, which two addends never ask for."""
    a, b, c, d = (r.randint(6, 39) for _ in range(4))
    return f"${a} + {b} + {c} + {d}$", fmt(a + b + c + d)


def dopelnienia(r):
    """Take away from a round number. The shortcut is to complement every digit
    against 9 and the last one against 10, which is why the minuend is round."""
    base = r.choice([100, 100, 200, 500, 1000, 1000])
    a = r.randint(base // 10, base - base // 10)
    return f"${fmt(base)} - {fmt(a)}$", fmt(base - a)


def dopelnienia_duze(r):
    """The same shortcut one order of magnitude out, where doing it by columns
    stops being an option and the complement is the only quick route."""
    base = r.choice([1000, 2000, 5000, 10000])
    a = r.randint(base // 10, base - base // 10)
    return f"${fmt(base)} - {fmt(a)}$", fmt(base - a)


def podwajanie(r):
    """Halving only ever gets an even number, so no answer needs a fraction."""
    if r.random() < 0.5:
        a = r.randint(23, 480)
        return f"podw\\'{{o}}j ${fmt(a)}$", fmt(2 * a)
    a = 2 * r.randint(23, 480)
    return f"po\\l{{}}owa z ${fmt(a)}$", fmt(a // 2)


def triki(r):
    """The four multiplications that have a shortcut worth owning: x11 (digits
    out, their sum in), x5 (half, then x10), x9 (x10 less one), x25 (quarter,
    then x100). x25 gets a multiple of four so the quarter stays whole."""
    k = r.choice([11, 11, 5, 5, 9, 25])
    a = 4 * r.randint(3, 40) if k == 25 else r.randint(12, 89)
    return rf"${fmt(a)} \times {k}$", fmt(a * k)


def triki_duze(r):
    """The same idea against the neighbours of a round number: x99 is x100 less
    one, x101 is x100 plus one, x15 is x10 plus half of it, x50 is half of
    x100. Each is one round multiplication and one correction."""
    k = r.choice([99, 101, 15, 50, 12, 20])
    a = 2 * r.randint(6, 45) if k == 15 else r.randint(12, 89)
    return rf"${fmt(a)} \times {k}$", fmt(a * k)


def dziesietne(r):
    """One decimal place, so lining up the point is the whole difficulty.

    Neither operand ever ends in a zero tenth: `15{,}0` is a whole number
    wearing a decimal's clothes, and a set that mixes the two forms is asking
    two different questions under one heading."""
    def operand():
        t = r.randint(11, 199)
        while t % 10 == 0:
            t = r.randint(11, 199)
        return t

    a, b = operand(), operand()
    if r.random() < 0.5:
        return f"${dec(a)} + {dec(b)}$", dect(a + b)
    if b > a:
        a, b = b, a
    return f"${dec(a)} - {dec(b)}$", dect(a - b)


def dziesietne_mnozenie(r):
    """A decimal times a whole number. The digits are the easy part; what the
    drill is for is deciding where the point lands, which is why the multiplier
    is never a power of ten."""
    t = r.randint(11, 98)
    while t % 10 == 0:
        t = r.randint(11, 98)
    k = r.randint(3, 9)
    return rf"${dec(t)} \times {k}$", dect(t * k)


def czesci(r):
    """A fraction of a number. The base is a multiple of the denominator, so
    the answer is always whole -- this drills the division, not the remainder."""
    num, den = r.choice([(1, 2), (1, 3), (1, 4), (1, 5),
                         (2, 3), (3, 4), (2, 5), (3, 5)])
    base = den * r.randint(4, 40)
    return f"${num}/{den}$ z ${fmt(base)}$", fmt(base * num // den)


def reszty(r):
    b = r.choice([3, 4, 5, 6, 7, 8, 9, 11])
    a = r.randint(20, 199)
    return rf"reszta z ${fmt(a)} \div {b}$", fmt(a % b)


def dzielenie_reszta(r):
    """Quotient AND remainder, which is what integer division actually returns
    and what reszty() deliberately throws half of away."""
    b = r.choice([3, 4, 5, 6, 7, 8, 9, 11, 12])
    a = r.randint(23, 199)
    while a % b == 0:
        a = r.randint(23, 199)
    return rf"${fmt(a)} \div {b}$ (całość i reszta)", f"{a // b} r. {a % b}"


def kolejnosc(r):
    """Order of operations: the answer differs if you go left to right."""
    shape = r.randint(0, 3)
    a, b, c = r.randint(2, 12), r.randint(2, 12), r.randint(2, 20)
    if shape == 0:
        return rf"${c} + {a} \times {b}$", fmt(c + a * b)
    if shape == 1:
        # sgn(), not fmt(): this shape can land below zero, and a bare `-8`
        # in the text-mode appendix prints a hyphen where the reader needs a
        # minus. The first edition shipped exactly one of those.
        return (rf"${c * a + b} - {a} \times {b // 2 + 1}$",
                sgn(c * a + b - a * (b // 2 + 1)))
    if shape == 2:
        return rf"$({a} + {b}) \times {c % 8 + 2}$", fmt((a + b) * (c % 8 + 2))
    q = r.randint(2, 9)
    return rf"${a * q} \div {q} + {b}$", fmt(a + b)


def kolejnosc_nawiasy(r):
    """Brackets and a square in the same line, so precedence has three levels
    rather than two and the bracket is no longer always first."""
    a, b, c = r.randint(2, 15), r.randint(2, 12), r.randint(2, 9)
    shape = r.randint(0, 3)
    if shape == 0:
        return rf"$({a} + {b}) \times {c} - {b}$", fmt((a + b) * c - b)
    if shape == 1:
        return rf"${c}^2 + {a} \times {b}$", fmt(c * c + a * b)
    if shape == 2:
        # Built from the quotient outwards, so the division inside the bracket
        # comes out exact -- the exercise is the ORDER, not a remainder.
        d, q = r.randint(2, 9), r.randint(2, 12)
        return (rf"$({fmt(d * q + b)} - {b}) \div {d} + {c}^2$", fmt(q + c * c))
    # sgn() for the same reason as kolejnosc(): a small a against a large c
    # puts this one below zero.
    return rf"${a} \times ({b} + {c}) - {c}^2$", sgn(a * (b + c) - c * c)


def procenty(r):
    p = r.choice([5, 10, 20, 25, 50])
    base = r.choice([20, 40, 60, 80, 100, 120, 140, 160, 180,
                     200, 240, 260, 300, 320, 400])
    return rf"${p}\%$ z ${fmt(base)}$", fmt(base * p // 100)


def procenty_trudne(r):
    """Every base is a multiple of twenty and every rate a multiple of five, so
    the result is whole without the drill ever having to say so."""
    p = r.choice([15, 30, 35, 40, 60, 75, 80, 90])
    base = r.choice([20, 40, 60, 80, 120, 140, 160, 180,
                     200, 240, 260, 300, 320, 400])
    return rf"${p}\%$ z ${fmt(base)}$", fmt(base * p // 100)


def procent_ile(r):
    """The percentage read backwards: the part and the whole are given and the
    rate is what is missing. Same three numbers, and most people who can do
    procenty() cannot do this one at speed."""
    p = r.choice([5, 10, 20, 25, 40, 50, 60, 75])
    base = r.choice([20, 40, 60, 80, 120, 160, 200, 240, 300, 400])
    return rf"${fmt(base * p // 100)}$ to ile \% z ${fmt(base)}$", f"{p}\\%"


def procent_bazy(r):
    """And the third way round: the rate and the part are given, the whole is
    missing. This is the one an invoice asks for."""
    p = r.choice([10, 20, 25, 40, 50, 75])
    base = r.choice([20, 40, 60, 80, 120, 160, 200, 240, 300, 400])
    return (rf"${p}\%$ liczby to ${fmt(base * p // 100)}$", fmt(base))


def podwyzki(r):
    """A percentage applied TO a number rather than taken FROM it, which is the
    shape a price change actually has."""
    p = r.choice([5, 10, 20, 25, 50])
    base = r.choice([20, 40, 60, 80, 120, 160, 200, 240, 300, 400])
    d = base * p // 100
    if r.random() < 0.5:
        return rf"${fmt(base)}$ w górę o ${p}\%$", fmt(base + d)
    return rf"${fmt(base)}$ w dół o ${p}\%$", fmt(base - d)


def kwadraty_konc5(r, n):
    """Squares of numbers ending in five, which have a shortcut worth owning:
    multiply the leading part by one more than itself and write 25 after it.
    Sampled over exactly n of them, so the reader meets each one once."""
    return [(f"${fmt(v)}^2$", fmt(v * v))
            for v in r.sample([10 * k + 5 for k in range(1, n + 1)], n)]


def roznica_kwadratow(r):
    """A pair straddling a round number, so (m-d)(m+d) is m^2 - d^2 and the
    whole thing is one square and one subtraction. The reader who multiplies it
    out the long way gets the same answer and a worse time, which is the
    point."""
    m = r.choice([20, 30, 40, 50, 60, 70, 80, 90, 100])
    d = r.randint(1, 9)
    return rf"${m - d} \times {m + d}$", fmt((m - d) * (m + d))


# Powers worth having by heart, and nothing beyond them: the doubling ladder as
# far as 4096, the small cubes, and the squares a reader meets in real work.
# Enumerated rather than drawn, because the useful ones do not form a range.
POWERS = ([(2, e) for e in range(2, 13)]
          + [(3, e) for e in range(2, 8)]
          + [(4, e) for e in range(2, 7)]
          + [(5, e) for e in range(2, 6)]
          + [(6, e) for e in (2, 3, 4)]
          + [(7, e) for e in (2, 3)]
          + [(8, e) for e in (2, 3)]
          + [(9, e) for e in (2, 3)]
          + [(10, e) for e in range(2, 6)]
          + [(11, e) for e in (2, 3)]
          + [(12, e) for e in (2, 3)]
          + [(b, 2) for b in (13, 14, 15, 16, 20, 25, 30)])


def potegi(r, n):
    return [(f"${b}^{{{e}}}$", fmt(b ** e)) for b, e in r.sample(POWERS, n)]


def kwadraty(r, n, lo=11):
    """Sampled, not drawn: the whole space is barely bigger than a set, so
    rejection would spend most of its draws on collisions -- and sampling means
    the reader meets each square exactly once."""
    return [(f"${a}^2$", fmt(a * a)) for a in r.sample(range(lo, lo + n), n)]


def pierwiastki(r, n, lo=4):
    """In words, not \\sqrt -- see the note above the builders."""
    return [(f"pierwiastek z ${fmt(a * a)}$", fmt(a))
            for a in r.sample(range(lo, lo + n), n)]


# Conversions written as an arrow rather than a sentence. The arrow fits three
# columns where "zamień 4 kilometry na metry" does not, and it says the same
# thing in every language, so nothing here has to be translated to be read.
UNITS = [("km", "m", 1000), ("m", "cm", 100), ("cm", "mm", 10),
         ("kg", "g", 1000), ("t", "kg", 1000), ("l", "ml", 1000),
         ("h", "min", 60), ("min", "s", 60)]


def jednostki(r):
    big, small, k = r.choice(UNITS)
    a = r.randint(2, 48)
    if r.random() < 0.5:
        return rf"${a}$ {big} $\rightarrow$ {small}", fmt(a * k)
    return rf"${fmt(a * k)}$ {small} $\rightarrow$ {big}", fmt(a)


def czas(r):
    """Minutes between two clock times. Asked in minutes rather than in hours
    and minutes so the answer is one number: `1 h 35 min` and `95 min` are the
    same answer written two ways, and a scored drill cannot accept both."""
    h1, m1 = r.randint(6, 19), r.choice([0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])
    dur = r.choice([r.randint(4, 12) * 5, r.randint(13, 36) * 5])
    end = h1 * 60 + m1 + dur
    return (f"od {h1}:{m1:02d} do {end // 60}:{end % 60:02d}", fmt(dur))


def srednia(r):
    """The mean of three or four numbers, built from the mean outwards so it
    comes out whole. A drill whose answers are recurring decimals measures
    handwriting."""
    k = r.choice([3, 3, 4])
    m = r.randint(8, 60)
    while True:
        d = [r.randint(-9, 9) for _ in range(k - 1)]
        d.append(-sum(d))
        xs = [m + x for x in d]
        if all(x > 0 for x in xs):
            break
    return "średnia z $" + "$, $".join(str(x) for x in xs) + "$", fmt(m)


def rownania(r):
    """One unknown, one step. Undoing an operation is a different motion from
    doing it, and a reader fluent in both directions of arithmetic is often
    fluent in only one of these."""
    x = r.randint(3, 60)
    shape = r.randint(0, 3)
    if shape == 0:
        a = r.randint(5, 80)
        return f"$x + {a} = {fmt(x + a)}$", fmt(x)
    if shape == 1:
        a = r.randint(5, 60)
        return f"$x - {a} = {x}$", fmt(x + a)
    if shape == 2:
        a = r.randint(2, 12)
        return f"${a}x = {fmt(a * x)}$", fmt(x)
    a = r.randint(2, 12)
    return rf"$x \div {a} = {x}$", fmt(a * x)


def ujemne(r):
    """Below zero, where a subtraction can be an addition and two minuses stop
    meaning what they mean above it."""
    a, b = r.randint(3, 40), r.randint(3, 40)
    shape = r.randint(0, 3)
    if shape == 0:
        return f"$-{a} + {b}$", sgn(b - a)
    if shape == 1:
        return f"${a} - {b}$", sgn(a - b)
    if shape == 2:
        c = r.randint(2, 9)
        return rf"$-{a} \times {c}$", sgn(-a * c)
    c = r.randint(2, 9)
    return rf"$-{fmt(a * c)} \div {c}$", sgn(-a)


DENS = (2, 3, 4, 5, 6, 8, 10, 12)


def frac_txt(f: Fraction) -> str:
    return fmt(f.numerator) if f.denominator == 1 else f"{f.numerator}/{f.denominator}"


def ulamki(r):
    """Fractions written with a slash, never \\frac -- see the note above the
    builders. One denominator always divides the other, so the common
    denominator is one of the two and finding it is not the exercise."""
    d1 = r.choice(DENS)
    d2 = r.choice([d for d in DENS if d % d1 == 0 or d1 % d == 0])
    n1, n2 = r.randint(1, d1 - 1), r.randint(1, d2 - 1)
    f1, f2 = Fraction(n1, d1), Fraction(n2, d2)
    if r.random() < 0.5:
        return f"${n1}/{d1} + {n2}/{d2}$", frac_txt(f1 + f2)
    if f2 > f1:
        f1, f2, n1, d1, n2, d2 = f2, f1, n2, d2, n1, d1
    if f1 == f2:
        return f"${n1}/{d1} + {n2}/{d2}$", frac_txt(f1 + f2)
    return f"${n1}/{d1} - {n2}/{d2}$", frac_txt(f1 - f2)


def nwd_nww(r):
    """Both kept small enough to be seen rather than computed: the drill is
    recognising the common factor, not running Euclid."""
    if r.random() < 0.5:
        a, b = r.randint(6, 60), r.randint(6, 60)
        return f"NWD$({a}, {b})$", fmt(gcd(a, b))
    a, b = r.randint(2, 15), r.randint(2, 15)
    return f"NWW$({a}, {b})$", fmt(a * b // gcd(a, b))


def podzielnosc(r):
    """Half the draws are built divisible on purpose. Left to chance a divisor
    of nine would answer `nie` eight times out of nine, and a reader who
    noticed that would score well without ever applying the rule."""
    d = r.choice([3, 4, 6, 8, 9, 11])
    if r.random() < 0.5:
        n = d * r.randint(12, 999)
    else:
        n = r.randint(100, 9999)
    return (f"czy ${fmt(n)}$ dzieli się przez ${d}$?",
            "tak" if n % d == 0 else "nie")


PLACES = {10: "dziesiątek", 100: "setek", 1000: "tysięcy"}


def zaokraglanie(r):
    """Never an exact half. Which way 3850 goes to hundreds is a convention,
    and a drill that scores a convention is scoring whether the reader was
    taught the same one."""
    place = r.choice([10, 100, 1000])
    n = r.randint(place, 100 * place)
    while n % place == place // 2:
        n = r.randint(place, 100 * place)
    return (f"${fmt(n)}$ do {PLACES[place]}",
            fmt(int(round(n / place)) * place))


def suma_cyfr(r):
    n = r.randint(1000, 99999)
    return f"suma cyfr ${fmt(n)}$", fmt(sum(int(c) for c in str(n)))


def ciag(r):
    """Five shapes, and the reader is not told which. Naming the rule is what
    makes the next term findable, so a set of one shape would only measure
    arithmetic."""
    kind = r.randint(0, 4)
    if kind == 0:
        a, d = r.randint(2, 30), r.randint(2, 12)
        xs = [a + i * d for i in range(5)]
    elif kind == 1:
        a, q = r.randint(2, 6), r.choice([2, 3])
        xs = [a * q ** i for i in range(5)]
    elif kind == 2:
        a = r.randint(1, 9)
        xs = [(a + i) ** 2 for i in range(5)]
    elif kind == 3:
        a, b = r.randint(1, 9), r.randint(2, 12)
        xs = [a, b]
        while len(xs) < 5:
            xs.append(xs[-1] + xs[-2])
    else:
        a, d = r.randint(2, 20), r.randint(1, 5)
        xs, step = [a], d
        while len(xs) < 5:
            xs.append(xs[-1] + step)
            step += d
    body = ", ".join(fmt(x) for x in xs[:-1])
    return f"${body}, \\ldots$", fmt(xs[-1])


ROMAN = ((100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
         (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"))


def to_roman(n: int) -> str:
    out = ""
    for v, s in ROMAN:
        while n >= v:
            out += s
            n -= v
    return out


def rzymskie(r):
    """Both directions, and nothing longer than eight letters: past that the
    exercise is transcription rather than arithmetic."""
    n = r.randint(4, 399)
    s = to_roman(n)
    while len(s) > 8:
        n = r.randint(4, 399)
        s = to_roman(n)
    if r.random() < 0.5:
        return f"{s}", fmt(n)
    return f"${fmt(n)}$ rzymskimi", s


def mieszane(r, draws):
    """Several builders in one set of exactly N, distinct across the whole set
    and not merely within each part."""
    seen, out = set(), []
    for count, draw in zip(split(N, len(draws)), draws):
        out += distinct(count, draw, seen)
    return out


# ------------------------------------------------------------------
#  Blok IV's builders. Nothing here is a wider range of something the book
#  already drills -- that is what the II and III sets are for. Each of these
#  asks for a step the earlier blocks deliberately kept out: an equation with
#  two moves in it, a common denominator that has to be found rather than
#  read off, a percentage applied twice, an operation done below zero.
# ------------------------------------------------------------------

def rownania_dwukrokowe(r):
    """Two moves, and the order of the two is the whole exercise: undo the
    addition before the multiplication, which is the reverse of the order the
    expression was built in."""
    x = r.randint(2, 30)
    a, b = r.randint(2, 12), r.randint(3, 40)
    if r.random() < 0.5:
        return f"${a}x + {b} = {fmt(a * x + b)}$", fmt(x)
    return f"${a}x - {b} = {fmt(a * x - b)}$", fmt(x)


def ulamki_rozne(r):
    """Denominators that do NOT divide one another, so the common denominator
    has to be built. ulamki() keeps one a multiple of the other on purpose --
    this is the step that program leaves out."""
    while True:
        d1, d2 = r.choice(DENS), r.choice(DENS)
        if d1 % d2 and d2 % d1:
            break
    n1, n2 = r.randint(1, d1 - 1), r.randint(1, d2 - 1)
    f1, f2 = Fraction(n1, d1), Fraction(n2, d2)
    if r.random() < 0.5:
        return f"${n1}/{d1} + {n2}/{d2}$", frac_txt(f1 + f2)
    if f2 > f1:
        f1, f2, n1, d1, n2, d2 = f2, f1, n2, d2, n1, d1
    return f"${n1}/{d1} - {n2}/{d2}$", frac_txt(f1 - f2)


def procent_skladany(r):
    """Two changes one after the other, which do not add up -- the second acts
    on what the first left. Up-then-down by the same rate never returns to the
    start, and that is the trap this set exists for."""
    # BOTH STEPS HAVE TO COME OUT WHOLE, and the draft only checked that the
    # arithmetic ran: `100` up 25 then up 10 is 137.5, which integer division
    # printed as 137. That is a wrong answer, not a rounded one -- a reader
    # doing it exactly gets a number the book says is not the number. Rejected
    # and redrawn instead, which costs a few draws and cannot be wrong.
    while True:
        base = r.choice([100, 200, 400, 500, 800, 1000, 1200, 2000])
        p, q = r.choice([10, 20, 25, 50]), r.choice([10, 20, 25, 50])
        up1, up2 = r.random() < 0.5, r.random() < 0.5
        v1 = base * (100 + p if up1 else 100 - p)
        if v1 % 100:
            continue
        v2 = (v1 // 100) * (100 + q if up2 else 100 - q)
        if v2 % 100:
            continue
        # WRITTEN AS SIGNED PERCENTAGES, NOT AS A SENTENCE. `1200 o 50% w
        # dół, potem o 25% w górę` is eleven words, and a set of forty of them
        # measures reading speed -- which is the one thing this book says it
        # is not measuring. `-50% +25%` says the same in the notation the
        # reader is already doing arithmetic in, and it fits three columns
        # where the sentence needed two.
        return (rf"${fmt(base)}$ ${'+' if up1 else '-'}{p}\%$ "
                rf"${'+' if up2 else '-'}{q}\%$", fmt(v2 // 100))


def szescienne(r, n):
    """Cube roots, in words for the reason the square roots are: nothing here
    emits a radical."""
    return [(f"pierwiastek sześcienny z ${fmt(a ** 3)}$", fmt(a))
            for a in r.sample(range(2, 2 + n), n)]


def kolejnosc_ujemne(r):
    """Order of operations below zero, where the sign of a product and the sign
    of a sum stop agreeing with each other."""
    a, b, c = r.randint(2, 12), r.randint(2, 12), r.randint(2, 15)
    shape = r.randint(0, 2)
    if shape == 0:
        return rf"$-{a} \times {b} + {c}$", sgn(-a * b + c)
    if shape == 1:
        return rf"${c} - {a} \times {b}$", sgn(c - a * b)
    # c is a multiple of a and so is a*b, so the bracket divides exactly. The
    # first draft guarded the non-dividing case by printing 0, which is a
    # wrong answer rather than a missing one -- checkanswers.py caught it.
    c = a * r.randint(1, 5)
    return rf"$({c} - {a * b}) \div {a}$", sgn((c - a * b) // a)


def proporcje(r):
    """A proportion with one term missing. Built from the ratio outwards so the
    answer is whole -- the exercise is seeing the ratio, not dividing badly."""
    k = r.randint(2, 12)
    a, b = r.randint(2, 9), r.randint(2, 9)
    return f"${a} : {b} = {fmt(a * k)} : ?$", fmt(b * k)


def srednia_wazona(r):
    """A weighted mean, where the naive answer is the mean of the two values
    and the right one is not."""
    v1, v2 = r.randint(2, 9) * 10, r.randint(2, 9) * 10
    w1, w2 = r.randint(1, 4), r.randint(1, 4)
    while (v1 * w1 + v2 * w2) % (w1 + w2):
        w1, w2 = r.randint(1, 4), r.randint(1, 4)
    return (f"${v1}$ z wagą ${w1}$, ${v2}$ z wagą ${w2}$",
            fmt((v1 * w1 + v2 * w2) // (w1 + w2)))


SQ_UNITS = [("m^2", "cm^2", 10000), ("km^2", "m^2", 1000000),
            ("ha", "m^2", 10000), ("cm^2", "mm^2", 100)]


def jednostki_kwadratowe(r):
    """Areas, where the factor is the length factor SQUARED -- which is the one
    conversion nearly everybody gets wrong by a factor of a hundred."""
    big, small, k = r.choice(SQ_UNITS)
    a = r.randint(2, 40)
    if r.random() < 0.5:
        return rf"${a}$ ${big}$ $\rightarrow$ ${small}$", fmt(a * k)
    return rf"${fmt(a * k)}$ ${small}$ $\rightarrow$ ${big}$", fmt(a)


def czas_dodawanie(r):
    """Adding two durations, where sixty is the base and the carry does not
    happen at ten."""
    h1, m1 = r.randint(0, 4), r.choice([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])
    h2, m2 = r.randint(0, 4), r.choice([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])
    t = (h1 * 60 + m1) + (h2 * 60 + m2)
    return (f"${h1}$ h ${m1}$ min $+$ ${h2}$ h ${m2}$ min",
            f"{t // 60} h {t % 60} min")


def dzielenie_dziesietne(r):
    """A decimal divided by a whole number, built from the quotient outwards so
    it comes out to one place and the drill is the point, not the remainder."""
    q = r.randint(11, 199)
    while q % 10 == 0:
        q = r.randint(11, 199)
    d = r.randint(2, 9)
    return rf"${dec(q * d)} \div {d}$", dect(q)


def potegi_dzialania(r):
    """Same base, so the exponents add or subtract and nothing is multiplied
    out. The whole point is not computing either side."""
    b = r.choice([2, 3, 5, 10])
    e1, e2 = r.randint(2, 6), r.randint(2, 5)
    if r.random() < 0.5:
        return rf"${b}^{{{e1}}} \times {b}^{{{e2}}}$", fmt(b ** (e1 + e2))
    e1 += e2
    return rf"${b}^{{{e1}}} \div {b}^{{{e2}}}$", fmt(b ** (e1 - e2))


def procent_zmiany(r):
    """From two numbers to the percentage between them. The base is the FIRST
    one, which is the half people drop."""
    # Same trap as procent_skladany: `150` up 25 is 187.5, and printing 187
    # makes the printed answer of 25\% false by a third of a point. Redraw
    # rather than round.
    while True:
        base = r.choice([20, 40, 50, 80, 100, 120, 150, 200, 250, 400])
        p = r.choice([10, 20, 25, 50, 75, 100])
        up = r.random() < 0.5
        v = base * (100 + p if up else 100 - p)
        if v % 100 or v == 0:
            continue
        # The set is titled `O ile procent`, so the question does not have to
        # ask again -- an arrow between the two numbers is the whole of it.
        return (rf"${fmt(base)} \rightarrow {fmt(v // 100)}$", f"{p}\%")


# ------------------------------------------------------------------
#  The sets, in the order the reader meets them.
#
#  The list IS the ladder, and it is now three blocks long because the book is
#  a three-month course: Fundament, Tempo, Wyzwanie. A block is a chapter, and
#  tools/gen_plan.py reads this list to lay the blocks over thirteen weeks --
#  which is why every set carries a FAMILY. Two sets of the same family on
#  consecutive days is blocked practice; the plan interleaves them, and it can
#  only do that if the list says what each set drills.
#
#  Renaming and reordering is free. A SEED IS NOT -- it is what makes set 7 the
#  same forty exercises this month as last month, which is the only reason
#  timing yourself against it twice means anything. Give a new set a new seed,
#  and never reuse or renumber an old one. Seeds 1001--1025 are the first
#  edition's; everything added for the three-month course takes 1101 upwards,
#  and the gap is deliberate so the two allocations cannot grow into each
#  other.
# ------------------------------------------------------------------

class Set(NamedTuple):
    name: str        # file stem, prefixed with its position in the book
    title: str       # printed at the head of the set
    block: int       # 1 Fundament, 2 Tempo, 3 Wyzwanie -- one chapter each
    stars: int
    secs: float      # SECONDS PER EXERCISE; the target time is secs * N
    cols: int
    seed: int
    family: str      # what it drills, for the plan's interleaving
    build: Callable
    wide: bool = False   # \zz rather than \z: a question that needs the width
    rows: int = 1        # scoring rows under the set; >1 for a set done again


SETS = [
    # ---------------------------------------------------------------
    #  Blok I -- Fundament. One star. Nothing here needs a method the
    #  reader does not already have; what it needs is speed.
    # ---------------------------------------------------------------
    Set("01-dodawanie-2c", "Dodawanie dwucyfrowe", 1, 1, 5, 3, 1001, "dodawanie",
        lambda r: distinct(N, lambda: dodawanie(r, 11, 99))),
    Set("02-odejmowanie-2c", "Odejmowanie dwucyfrowe", 1, 1, 5, 3, 1002, "odejmowanie",
        lambda r: distinct(N, lambda: odejmowanie(r, 11, 99))),
    Set("03-mnozenie-tabliczka", "Tabliczka mnożenia", 1, 1, 4, 3, 1003, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 2, 9, 2, 9))),
    Set("04-dzielenie-tabliczka", "Dzielenie w tabliczce", 1, 1, 5, 3, 1004, "dzielenie",
        lambda r: distinct(N, lambda: dzielenie(r, 2, 9, 2, 9))),
    Set("05-dopelnienia", "Dopełnienia do okrągłych", 1, 1, 4.5, 3, 1015, "dopelnienia",
        lambda r: distinct(N, lambda: dopelnienia(r))),
    Set("06-podwajanie", "Podwajanie i połowienie", 1, 1, 4.5, 2, 1016, "podwajanie",
        lambda r: distinct(N, lambda: podwajanie(r))),
    Set("07-dodawanie-2c-b", "Dodawanie dwucyfrowe II", 1, 1, 5, 3, 1101, "dodawanie",
        lambda r: distinct(N, lambda: dodawanie(r, 11, 99))),
    Set("08-mnozenie-tabliczka-b", "Tabliczka mnożenia II", 1, 1, 4, 3, 1102, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 2, 9, 2, 9))),
    Set("09-cztery-skladniki", "Cztery składniki", 1, 1, 6, 3, 1103, "dodawanie",
        lambda r: distinct(N, lambda: cztery_skladniki(r))),
    Set("10-odejmowanie-2c-b", "Odejmowanie dwucyfrowe II", 1, 1, 5, 3, 1104, "odejmowanie",
        lambda r: distinct(N, lambda: odejmowanie(r, 11, 99))),
    Set("11-jednostki", "Jednostki", 1, 1, 5, 3, 1105, "jednostki",
        lambda r: distinct(N, lambda: jednostki(r))),
    Set("12-dzielenie-tabliczka-b", "Dzielenie w tabliczce II", 1, 1, 5, 3, 1106, "dzielenie",
        lambda r: distinct(N, lambda: dzielenie(r, 2, 9, 2, 9))),
    Set("13-rownania", "Równania jednokrokowe", 1, 1, 5.5, 3, 1107, "rownania",
        lambda r: distinct(N, lambda: rownania(r))),
    Set("14-ujemne", "Liczby ujemne", 1, 1, 5.5, 3, 1108, "ujemne",
        lambda r: distinct(N, lambda: ujemne(r))),
    Set("15-dopelnienia-b", "Dopełnienia do okrągłych II", 1, 1, 4.5, 3, 1109, "dopelnienia",
        lambda r: distinct(N, lambda: dopelnienia(r))),
    Set("16-suma-cyfr", "Suma cyfr", 1, 1, 5, 2, 1110, "cyfry",
        lambda r: distinct(N, lambda: suma_cyfr(r))),
    Set("17-mnozenie-tabliczka-c", "Tabliczka mnożenia III", 1, 1, 4, 3, 1111, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 2, 9, 2, 9))),
    Set("18-czas", "Ile minut", 1, 1, 6, 2, 1112, "czas",
        lambda r: distinct(N, lambda: czas(r))),
    Set("19-podwajanie-b", "Podwajanie i połowienie II", 1, 1, 4.5, 2, 1113, "podwajanie",
        lambda r: distinct(N, lambda: podwajanie(r))),
    Set("20-zaokraglanie", "Zaokrąglanie", 1, 1, 5, 2, 1114, "zaokraglanie",
        lambda r: distinct(N, lambda: zaokraglanie(r))),
    Set("21-dodawanie-2c-c", "Dodawanie dwucyfrowe III", 1, 1, 5, 3, 1115, "dodawanie",
        lambda r: distinct(N, lambda: dodawanie(r, 11, 99))),
    Set("22-odejmowanie-2c-c", "Odejmowanie dwucyfrowe III", 1, 1, 5, 3, 1116, "odejmowanie",
        lambda r: distinct(N, lambda: odejmowanie(r, 11, 99))),
    Set("23-jednostki-b", "Jednostki II", 1, 1, 5, 3, 1117, "jednostki",
        lambda r: distinct(N, lambda: jednostki(r))),
    Set("24-mieszane-start", "Mieszane — start", 1, 1, 5.5, 3, 1118, "mieszane",
        lambda r: mieszane(r, [
            lambda: dodawanie(r, 11, 99),
            lambda: odejmowanie(r, 11, 99),
            lambda: mnozenie(r, 2, 9, 2, 9),
            lambda: dzielenie(r, 2, 9, 2, 9),
        ])),

    # ---------------------------------------------------------------
    #  Blok II -- Tempo. Two stars. Three digits, percentages, decimals,
    #  remainders: the working range, and where most of the book lives.
    # ---------------------------------------------------------------
    Set("25-dodawanie-3c", "Dodawanie trzycyfrowe", 2, 2, 8, 3, 1005, "dodawanie",
        lambda r: distinct(N, lambda: dodawanie(r, 101, 899))),
    Set("26-odejmowanie-3c", "Odejmowanie trzycyfrowe", 2, 2, 8, 3, 1006, "odejmowanie",
        lambda r: distinct(N, lambda: odejmowanie(r, 101, 899))),
    Set("27-mnozenie-2x1", "Mnożenie dwucyfrowe przez jednocyfrowe", 2, 2, 8, 3, 1007, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 12, 99, 3, 9))),
    Set("28-dzielenie-3c", "Dzielenie trzycyfrowe", 2, 2, 9, 3, 1008, "dzielenie",
        lambda r: distinct(N, lambda: dzielenie(r, 3, 12, 11, 40))),
    Set("29-trzy-skladniki", "Trzy składniki", 2, 2, 9, 3, 1017, "dodawanie",
        lambda r: distinct(N, lambda: trzy_skladniki(r))),
    Set("30-triki-mnozenia", "Mnożenie na skróty", 2, 2, 6.75, 3, 1018, "triki",
        lambda r: distinct(N, lambda: triki(r))),
    Set("31-reszty", "Reszty z dzielenia", 2, 2, 7.5, 2, 1020, "reszty",
        lambda r: distinct(N, lambda: reszty(r))),
    Set("32-pierwiastki", "Pierwiastki kwadratowe", 2, 2, 6, 2, 1021, "pierwiastki",
        lambda r: pierwiastki(r, N)),
    Set("33-procenty", "Procenty w pamięci", 2, 2, 8, 3, 1010, "procenty",
        lambda r: distinct(N, lambda: procenty(r))),
    Set("34-czesci", "Części liczby", 2, 2, 7.5, 3, 1019, "czesci",
        lambda r: distinct(N, lambda: czesci(r))),
    Set("35-dziesietne", "Ułamki dziesiętne", 2, 2, 7.5, 3, 1022, "dziesietne",
        lambda r: distinct(N, lambda: dziesietne(r))),
    Set("36-kolejnosc", "Kolejność działań", 2, 2, 12.5, 2, 1009, "kolejnosc",
        lambda r: distinct(N, lambda: kolejnosc(r))),
    Set("37-mieszane-szybkie", "Mieszane — szybkie", 2, 2, 9, 3, 1013, "mieszane",
        lambda r: mieszane(r, [
            lambda: dodawanie(r, 11, 99),
            lambda: odejmowanie(r, 11, 99),
            lambda: mnozenie(r, 3, 12, 3, 9),
            lambda: dzielenie(r, 2, 9, 3, 12),
        ])),
    Set("38-dodawanie-3c-b", "Dodawanie trzycyfrowe II", 2, 2, 8, 3, 1119, "dodawanie",
        lambda r: distinct(N, lambda: dodawanie(r, 101, 899))),
    Set("39-odejmowanie-3c-b", "Odejmowanie trzycyfrowe II", 2, 2, 8, 3, 1120, "odejmowanie",
        lambda r: distinct(N, lambda: odejmowanie(r, 101, 899))),
    Set("40-mnozenie-2x1-b", "Mnożenie dwucyfrowe przez jednocyfrowe II", 2, 2, 8, 3, 1121, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 12, 99, 3, 9))),
    Set("41-dzielenie-3c-b", "Dzielenie trzycyfrowe II", 2, 2, 9, 3, 1122, "dzielenie",
        lambda r: distinct(N, lambda: dzielenie(r, 3, 12, 11, 40))),
    Set("42-triki-mnozenia-b", "Mnożenie na skróty II", 2, 2, 6.75, 3, 1123, "triki",
        lambda r: distinct(N, lambda: triki(r))),
    Set("43-roznica-kwadratow", "Para wokół okrągłej", 2, 2, 7, 3, 1124, "roznica-kwadratow",
        lambda r: distinct(N, lambda: roznica_kwadratow(r))),
    Set("44-procenty-b", "Procenty w pamięci II", 2, 2, 8, 3, 1125, "procenty",
        lambda r: distinct(N, lambda: procenty(r))),
    Set("45-reszty-b", "Reszty z dzielenia II", 2, 2, 7.5, 2, 1126, "reszty",
        lambda r: distinct(N, lambda: reszty(r))),
    Set("46-ulamki", "Ułamki zwykłe", 2, 2, 8, 3, 1127, "ulamki",
        lambda r: distinct(N, lambda: ulamki(r))),
    Set("47-dziesietne-b", "Ułamki dziesiętne II", 2, 2, 7.5, 3, 1128, "dziesietne",
        lambda r: distinct(N, lambda: dziesietne(r))),
    Set("48-srednia", "Średnia", 2, 2, 9, 2, 1129, "srednia",
        lambda r: distinct(N, lambda: srednia(r)), True),
    Set("49-czesci-b", "Części liczby II", 2, 2, 7.5, 3, 1130, "czesci",
        lambda r: distinct(N, lambda: czesci(r))),
    Set("50-potegi", "Potęgi", 2, 2, 7, 3, 1131, "potegi",
        lambda r: potegi(r, N)),
    Set("51-nwd-nww", "NWD i NWW", 2, 2, 8, 3, 1132, "nwd",
        lambda r: distinct(N, lambda: nwd_nww(r))),
    Set("52-trzy-skladniki-b", "Trzy składniki II", 2, 2, 9, 3, 1133, "dodawanie",
        lambda r: distinct(N, lambda: trzy_skladniki(r))),
    Set("53-podzielnosc", "Podzielność", 2, 2, 7, 2, 1134, "podzielnosc",
        lambda r: distinct(N, lambda: podzielnosc(r)), True),
    Set("54-procent-ile", "Ile to procent", 2, 2, 9, 2, 1135, "procent-ile",
        lambda r: distinct(N, lambda: procent_ile(r)), True),
    Set("55-dzielenie-reszta", "Dzielenie z resztą", 2, 2, 9, 2, 1136, "dzielenie-reszta",
        lambda r: distinct(N, lambda: dzielenie_reszta(r))),
    Set("56-rzymskie", "Liczby rzymskie", 2, 2, 7, 2, 1137, "rzymskie",
        lambda r: distinct(N, lambda: rzymskie(r))),
    Set("57-kolejnosc-b", "Kolejność działań II", 2, 2, 12.5, 2, 1138, "kolejnosc",
        lambda r: distinct(N, lambda: kolejnosc(r))),
    Set("58-mieszane-tempo", "Mieszane — tempo", 2, 2, 9, 3, 1139, "mieszane",
        lambda r: mieszane(r, [
            lambda: dodawanie(r, 101, 899),
            lambda: mnozenie(r, 12, 99, 3, 9),
            lambda: procenty(r),
            lambda: reszty(r),
        ])),

    # ---------------------------------------------------------------
    #  Blok III -- Wyzwanie. Three stars. Four digits, two-digit products,
    #  brackets, and the percentage read backwards.
    # ---------------------------------------------------------------
    Set("59-kwadraty", "Kwadraty", 3, 3, 10, 3, 1011, "kwadraty",
        lambda r: kwadraty(r, N)),
    Set("60-mnozenie-3x1", "Mnożenie trzycyfrowe przez jednocyfrowe", 3, 3, 12, 3, 1023, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 102, 899, 3, 9))),
    Set("61-mnozenie-2x2", "Mnożenie dwucyfrowe", 3, 3, 15, 3, 1012, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 12, 49, 12, 49))),
    Set("62-procenty-trudne", "Procenty — trudniejsze", 3, 3, 9.75, 3, 1024, "procenty",
        lambda r: distinct(N, lambda: procenty_trudne(r))),
    Set("63-mieszane-dluzsze", "Mieszane — dłuższe", 3, 3, 13.5, 2, 1014, "mieszane",
        lambda r: mieszane(r, [
            lambda: dodawanie(r, 101, 999),
            lambda: odejmowanie(r, 101, 999),
            lambda: kolejnosc(r),
            lambda: procenty(r),
        ])),
    Set("64-mieszane-final", "Mieszane — finał", 3, 3, 16.5, 2, 1025, "mieszane",
        lambda r: mieszane(r, [
            lambda: mnozenie(r, 12, 49, 12, 49),
            lambda: dzielenie(r, 3, 12, 11, 40),
            lambda: procenty_trudne(r),
            lambda: dziesietne(r),
            lambda: kolejnosc(r),
        ])),
    Set("65-dodawanie-4c", "Dodawanie czterocyfrowe", 3, 3, 12, 3, 1140, "dodawanie",
        lambda r: distinct(N, lambda: dodawanie(r, 1001, 8999))),
    Set("66-odejmowanie-4c", "Odejmowanie czterocyfrowe", 3, 3, 12, 3, 1141, "odejmowanie",
        lambda r: distinct(N, lambda: odejmowanie(r, 1001, 8999))),
    Set("67-kwadraty-konc5", "Kwadraty piątek", 3, 3, 10, 3, 1142, "kwadraty-5",
        lambda r: kwadraty_konc5(r, N)),
    Set("68-mnozenie-2x2-b", "Mnożenie dwucyfrowe II", 3, 3, 15, 3, 1143, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 12, 49, 12, 49))),
    Set("69-dopelnienia-duze", "Dopełnienia do tysięcy", 3, 3, 9, 3, 1144, "dopelnienia",
        lambda r: distinct(N, lambda: dopelnienia_duze(r))),
    Set("70-mnozenie-3x1-b", "Mnożenie trzycyfrowe przez jednocyfrowe II", 3, 3, 12, 3, 1145, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 102, 899, 3, 9))),
    Set("71-kwadraty-b", "Kwadraty II", 3, 3, 12, 3, 1146, "kwadraty",
        lambda r: kwadraty(r, N, 51)),
    Set("72-triki-duze", "Mnożenie na skróty III", 3, 3, 9, 3, 1147, "triki",
        lambda r: distinct(N, lambda: triki_duze(r))),
    Set("73-pierwiastki-b", "Pierwiastki kwadratowe II", 3, 3, 8, 2, 1148, "pierwiastki",
        lambda r: pierwiastki(r, N, 20)),
    Set("74-dziesietne-mnozenie", "Dziesiętne razy całkowita", 3, 3, 10, 3, 1149, "dziesietne",
        lambda r: distinct(N, lambda: dziesietne_mnozenie(r))),
    Set("75-kolejnosc-nawiasy", "Nawiasy i potęgi", 3, 3, 14, 2, 1150, "kolejnosc",
        lambda r: distinct(N, lambda: kolejnosc_nawiasy(r))),
    Set("76-procent-bazy", "Procent — szukana całość", 3, 3, 10, 2, 1151, "procent-bazy",
        lambda r: distinct(N, lambda: procent_bazy(r)), True),
    Set("77-podwyzki", "Podwyżki i obniżki", 3, 3, 10, 2, 1152, "podwyzki",
        lambda r: distinct(N, lambda: podwyzki(r)), True),
    Set("78-dzielenie-4c", "Dzielenie czterocyfrowe", 3, 3, 13, 3, 1153, "dzielenie",
        lambda r: distinct(N, lambda: dzielenie(r, 3, 12, 101, 799))),
    Set("79-ciagi", "Ciągi — następny wyraz", 3, 3, 12, 2, 1154, "ciagi",
        lambda r: distinct(N, lambda: ciag(r)), True),
    Set("80-procenty-trudne-b", "Procenty — trudniejsze II", 3, 3, 9.75, 3, 1155, "procenty",
        lambda r: distinct(N, lambda: procenty_trudne(r))),
    Set("81-mieszane-final-b", "Mieszane — finał II", 3, 3, 16.5, 2, 1156, "mieszane",
        lambda r: mieszane(r, [
            lambda: mnozenie(r, 12, 49, 12, 49),
            lambda: dzielenie(r, 3, 12, 11, 40),
            lambda: procenty_trudne(r),
            lambda: kolejnosc_nawiasy(r),
            lambda: dziesietne(r),
        ])),

    # ---------------------------------------------------------------
    #  Blok IV -- Mistrzostwo. The fourth month, and nothing in it is a wider
    #  range of something the earlier blocks already drill -- that is what
    #  their own second and third sets are for. Each set here asks for a step
    #  the ladder deliberately kept out: two moves in an equation, a common
    #  denominator that has to be built, a percentage applied twice, an
    #  operation carried out below zero.
    # ---------------------------------------------------------------
    Set("82-rownania-dwukrokowe", "Równania dwukrokowe", 4, 3, 9, 3, 1201, "rownania-2",
        lambda r: distinct(N, lambda: rownania_dwukrokowe(r))),
    Set("83-ulamki-rozne", "Ułamki o różnych mianownikach", 4, 3, 10, 3, 1202, "ulamki-rozne",
        lambda r: distinct(N, lambda: ulamki_rozne(r))),
    Set("84-mnozenie-2x2-duze", "Mnożenie dwucyfrowe — duże", 4, 3, 18, 3, 1203, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 51, 99, 51, 99))),
    Set("85-procent-skladany", "Procent składany", 4, 3, 13, 3, 1204, "procent-skladany",
        lambda r: distinct(N, lambda: procent_skladany(r))),
    Set("86-szescienne", "Pierwiastki sześcienne", 4, 3, 10, 2, 1205, "szescienne",
        lambda r: szescienne(r, N)),
    Set("87-kolejnosc-ujemne", "Kolejność działań poniżej zera", 4, 3, 11, 2, 1206, "kolejnosc-ujemne",
        lambda r: distinct(N, lambda: kolejnosc_ujemne(r))),
    Set("88-proporcje", "Proporcje", 4, 3, 9, 3, 1207, "proporcje",
        lambda r: distinct(N, lambda: proporcje(r))),
    Set("89-potegi-dzialania", "Działania na potęgach", 4, 3, 9, 3, 1208, "potegi-dzialania",
        lambda r: distinct(N, lambda: potegi_dzialania(r))),
    Set("90-jednostki-kwadratowe", "Jednostki kwadratowe", 4, 3, 10, 2, 1209, "jednostki-kw",
        lambda r: distinct(N, lambda: jednostki_kwadratowe(r))),
    Set("91-czas-dodawanie", "Dodawanie czasu", 4, 3, 10, 2, 1210, "czas-dodawanie",
        lambda r: distinct(N, lambda: czas_dodawanie(r)), True),
    Set("92-dzielenie-dziesietne", "Dzielenie dziesiętnych", 4, 3, 11, 3, 1211, "dziesietne",
        lambda r: distinct(N, lambda: dzielenie_dziesietne(r))),
    Set("93-srednia-wazona", "Średnia ważona", 4, 3, 13, 2, 1212, "srednia-wazona",
        lambda r: distinct(N, lambda: srednia_wazona(r)), True),
    Set("94-procent-zmiany", "O ile procent", 4, 3, 12, 3, 1213, "procent-zmiany",
        lambda r: distinct(N, lambda: procent_zmiany(r))),
    Set("95-dodawanie-5c", "Dodawanie pięciocyfrowe", 4, 3, 15, 3, 1214, "dodawanie",
        lambda r: distinct(N, lambda: dodawanie(r, 10001, 89999))),
    Set("96-odejmowanie-5c", "Odejmowanie pięciocyfrowe", 4, 3, 15, 3, 1215, "odejmowanie",
        lambda r: distinct(N, lambda: odejmowanie(r, 10001, 89999))),
    Set("97-mnozenie-3x2", "Mnożenie trzycyfrowe przez dwucyfrowe", 4, 3, 20, 3, 1216, "mnozenie",
        lambda r: distinct(N, lambda: mnozenie(r, 102, 499, 12, 29))),
    Set("98-kwadraty-3c", "Kwadraty trzycyfrowe", 4, 3, 16, 3, 1217, "kwadraty",
        lambda r: kwadraty(r, N, 91)),
    Set("99-dzielenie-5c", "Dzielenie pięciocyfrowe", 4, 3, 16, 3, 1218, "dzielenie",
        lambda r: distinct(N, lambda: dzielenie(r, 12, 49, 201, 999))),
    Set("100-triki-mistrz", "Mnożenie na skróty IV", 4, 3, 9, 3, 1219, "triki",
        lambda r: distinct(N, lambda: triki_duze(r))),
    Set("101-ulamki-rozne-b", "Ułamki o różnych mianownikach II", 4, 3, 10, 3, 1220, "ulamki-rozne",
        lambda r: distinct(N, lambda: ulamki_rozne(r))),
    Set("102-kolejnosc-nawiasy-b", "Nawiasy i potęgi II", 4, 3, 14, 2, 1221, "kolejnosc",
        lambda r: distinct(N, lambda: kolejnosc_nawiasy(r))),
    Set("103-procent-skladany-b", "Procent składany II", 4, 3, 13, 3, 1222, "procent-skladany",
        lambda r: distinct(N, lambda: procent_skladany(r))),
    Set("104-mieszane-mistrz", "Mieszane — mistrzostwo", 4, 3, 12, 3, 1223, "mieszane",
        lambda r: mieszane(r, [
            lambda: rownania_dwukrokowe(r),
            lambda: ulamki_rozne(r),
            lambda: potegi_dzialania(r),
            lambda: kolejnosc_ujemne(r),
            lambda: proporcje(r),
        ])),
    Set("105-mieszane-mistrz-b", "Mieszane — mistrzostwo II", 4, 3, 14, 3, 1224, "mieszane",
        lambda r: mieszane(r, [
            lambda: mnozenie(r, 51, 99, 51, 99),
            lambda: dzielenie_dziesietne(r),
            lambda: proporcje(r),
            lambda: potegi_dzialania(r),
        ])),

    # ---------------------------------------------------------------
    #  Pomiary kontrolne -- one per block, and the only sets in the book
    #  designed to be done REPEATEDLY. Each carries five scoring rows
    #  instead of one, because a single measurement of anything says
    #  nothing and this book's whole argument is the second measurement.
    #
    #  One per block rather than one for the book: a benchmark is only
    #  informative over material the reader is actually drilling that
    #  month, and an easy mixed set re-done in week 13 measures how bored
    #  they were rather than how fast they got.
    # ---------------------------------------------------------------
    Set("110-kontrolny-1", "Pomiar kontrolny I", 9, 1, 5.5, 3, 1157, "kontrolny",
        lambda r: mieszane(r, [
            lambda: dodawanie(r, 11, 99),
            lambda: odejmowanie(r, 11, 99),
            lambda: mnozenie(r, 2, 9, 2, 9),
            lambda: dzielenie(r, 2, 9, 2, 9),
        ]), rows=5),
    Set("111-kontrolny-2", "Pomiar kontrolny II", 9, 2, 9, 3, 1158, "kontrolny",
        lambda r: mieszane(r, [
            lambda: dodawanie(r, 101, 899),
            lambda: mnozenie(r, 12, 99, 3, 9),
            lambda: procenty(r),
            lambda: reszty(r),
            lambda: czesci(r),
        ]), rows=5),
    Set("112-kontrolny-3", "Pomiar kontrolny III", 9, 3, 14, 2, 1159, "kontrolny",
        lambda r: mieszane(r, [
            lambda: mnozenie(r, 12, 49, 12, 49),
            lambda: dzielenie(r, 3, 12, 11, 40),
            lambda: procenty_trudne(r),
            lambda: kolejnosc(r),
            lambda: dziesietne(r),
        ]), rows=5),
    Set("113-kontrolny-4", "Pomiar kontrolny IV", 9, 3, 13, 2, 1225, "kontrolny",
        lambda r: mieszane(r, [
            lambda: rownania_dwukrokowe(r),
            lambda: ulamki_rozne(r),
            lambda: potegi_dzialania(r),
            lambda: proporcje(r),
            lambda: kolejnosc_ujemne(r),
        ]), rows=5),
]


class Hand(NamedTuple):
    """A hand-written set. The generator never writes one and never reads its
    exercises -- what it needs is the METADATA, because the plan lays days over
    the whole book and a day that names a puzzle set has to name it correctly.

    Keeping this list here rather than in the plan is the same argument the
    include list has always made: two lists of the book's contents drift, and
    the one nobody builds from drifts silently."""
    name: str        # file stem under book/sets/
    title: str
    stars: int
    target: str      # its own, in mm:ss -- these are not N exercises long
    family: str
    count: int       # exercises, for the plan to be honest about the session


HAND = [
    Hand("20-zagadki", "Zagadki logiczne", 2, "15:00", "zagadki", 16),
    Hand("21-ciagi", "Ciągi i wzorce", 2, "10:00", "ciagi", 16),
    Hand("22-mieszane", "Wyzwania mieszane", 3, "18:00", "wyzwania", 16),
    Hand("23-triki", "Szybkie triki", 2, "9:00", "triki-reczne", 16),
]

# The chapters, in the order the book prints them. A set's NUMBER is its
# position in this order, which is why the plan cannot compute one without it.
# The difficulty blocks take 1 upwards and the two chapters that are not one
# take 8 and 9, so a fifth block can be added without moving either of them.
# Chapter order is this dict's key order, and a set's NUMBER is its position in
# that order -- which is why gen_plan.py cannot compute one without it.
BLOCK_TITLES = {1: "Fundament", 2: "Tempo", 3: "Wyzwanie", 4: "Mistrzostwo",
                8: "Łamigłówki", 9: "Pomiary kontrolne"}


class Item(NamedTuple):
    """One set as the plan sees it: a number, a name and how long it should
    take. Generated and hand-written sets differ in everything else and in
    none of this."""
    num: int
    name: str
    title: str
    stars: int
    target: str
    family: str
    block: int
    count: int


def book_order() -> list[Item]:
    """Every set in the book, numbered as the reader will see it numbered.

    The `zestaw` counter is global and steps once per set in file order, so
    this list and the printed numbers are the same thing computed twice -- and
    that is exactly why nothing else may hold a second copy of the order.
    """
    out, n = [], 0
    for b in sorted(BLOCK_TITLES):
        pool = HAND if b == 8 else [s for s in SETS if s.block == b]
        for x in pool:
            n += 1
            out.append(Item(n, x.name, x.title, x.stars,
                            x.target if isinstance(x, Hand) else target(x.secs),
                            x.family, b, x.count if isinstance(x, Hand) else N))
    return out


def render(s: Set) -> str:
    r = random.Random(s.seed)
    items = s.build(r)

    # The column break is written here, not left to the typesetter. A set is
    # laid out as one unbreakable row of boxes so that it cannot be split from
    # its own scoring box (see book/preamble.tex), and that means something has
    # to say where each box ends. split() balances them: forty over three
    # columns is 14/13/13, not 14/14/12.
    macro = "zz" if s.wide else "z"
    body, at = "", 0
    for i, count in enumerate(split(len(items), s.cols)):
        if i:
            body += "  \\btnc\n"
        for q, a in items[at:at + count]:
            body += f"  \\{macro}{{{q}}}{{{a}}}\n"
        at += count

    return HEADER.format(seed=s.seed, title=s.title, stars=s.stars,
                         target=target(s.secs), cols=s.cols, body=body,
                         opt="" if s.rows == 1 else f"[{s.rows}]")


def audit() -> None:
    """Two things the tree cannot show and no build would ever complain about.

    A REPEATED SEED is two sets carrying the same forty exercises under two
    titles -- the reader drills the same page twice and the second timing is
    not a second measurement. At twenty-five sets that was visible by eye; at
    eighty-one, written in blocks and copied from each other, it is not.

    A REPEATED NAME silently drops a set: the later one overwrites the earlier
    file, the include list names it once, and the book is one set short with
    every gate green.
    """
    for what, seen in (("seed", Counter(s.seed for s in SETS)),
                       ("name", Counter(s.name for s in SETS))):
        dupes = [k for k, n in seen.items() if n > 1]
        if dupes:
            raise SystemExit(f"gen_sets: repeated {what}(s): "
                             + ", ".join(str(d) for d in sorted(dupes)))
    # A hand-written set is named here and written by a person, so the one
    # thing this can check is that the file the include list will point at
    # actually exists -- otherwise the failure is a LaTeX error naming a path.
    for h in HAND:
        if not (ROOT / "book" / "sets" / f"{h.name}.tex").exists():
            raise SystemExit(f"gen_sets: HAND names {h.name}.tex, "
                             f"which is not in book/sets/")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true")
    a = p.parse_args()

    audit()
    OUT.mkdir(parents=True, exist_ok=True)
    stale, total = [], 0
    for s in SETS:
        text = render(s)
        total += text.count("\\z{") + text.count("\\zz{")
        dest = OUT / f"{s.name}.tex"
        cur = dest.read_text(encoding="utf8") if dest.exists() else None
        if cur == text:
            continue
        if a.check:
            stale.append(dest.relative_to(ROOT))
        else:
            dest.write_text(text, encoding="utf8")

    # The include lists are generated too, one per block, because a block is a
    # chapter: a set added to SETS and forgotten in structure.tex is a set
    # nobody ever sees, and every other check passes.
    # Each \input is preceded by the number the set will carry, and the set
    # refuses to typeset under any other one. That is what lets the plan print
    # `Zestaw 41` as a literal: the number it computes and the number LaTeX
    # steps to are the same thing worked out twice, and reordering a chapter in
    # structure.tex would otherwise send every row of the plan one set off,
    # silently, with every other gate green.
    lists, order = {}, {i.name: i.num for i in book_order()}
    for b in sorted(BLOCK_TITLES):
        pool = ([(h.name, f"sets/{h.name}") for h in HAND] if b == 8
                else [(s.name, f"sets/generated/{s.name}")
                      for s in SETS if s.block == b])
        body = "".join(f"\\btexpect{{{order[n]}}}\\input{{{path}}}\n"
                       for n, path in pool)
        lists[f"_blok-{b}.tex"] = (
            "% GENERATED by tools/gen_sets.py -- do not edit.\n" + body)
    for fname, text in lists.items():
        dest = OUT / fname
        cur = dest.read_text(encoding="utf8") if dest.exists() else None
        if cur == text:
            continue
        if a.check:
            stale.append(dest.relative_to(ROOT))
        else:
            dest.write_text(text, encoding="utf8")

    # And the other direction. Renaming a set leaves the old file behind, and
    # nothing above would ever look at it again: it is not in a block list, so
    # it is not in the book, and it is not in SETS, so no check compares it. It
    # would sit in the tree looking like a set the book contains.
    keep = {f"{s.name}.tex" for s in SETS} | set(lists)
    for f in sorted(OUT.glob("*.tex")):
        if f.name in keep:
            continue
        if a.check:
            stale.append(f.relative_to(ROOT))
        else:
            f.unlink()

    if stale:
        for s2 in stale:
            print(f"  STALE   {s2}")
        print(f"\n{len(stale)} generated file(s) out of date. Run `make sets`.")
        return 1

    order = book_order()
    for b, name in BLOCK_TITLES.items():
        xs = [i for i in order if i.block == b]
        print(f"  blok {b} {name:<18} zestawy {xs[0].num:>2}-{xs[-1].num:<3}"
              f" {len(xs):>3} sets, {sum(i.count for i in xs):>5} exercises")
    print(f"  {'':<25}{len(order):>13} sets, "
          f"{sum(i.count for i in order):>5} exercises")
    return 0


if __name__ == "__main__":
    sys.exit(main())
