#!/usr/bin/env python3
"""Generate the book's drill sets.

WHY GENERATED. This book is scored on how many exercises you get through and
how fast, so it needs hundreds of them, and hundreds of hand-written sums is
both a waste of a person and a place for arithmetic slips to hide. Everything
here is produced and its answer computed by the same three lines, so a printed
answer cannot disagree with its printed question.

DETERMINISTIC. Every set seeds its own Random with a fixed integer, so the book
is byte-identical on every machine and every run. A drill book whose pages
change under you cannot be re-run to compare times, which is the one thing this
book is for.

    tools/gen_sets.py            # write book/sets/generated/
    tools/gen_sets.py --check    # fail if the tree is stale

Hand-written sets -- logic, sequences, tricks -- live in book/sets/ and are not
touched by this script. Those cannot be generated: a word trap is a joke, and a
joke has an author.
"""
from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "book" / "sets" / "generated"

HEADER = """\
% ======================================================
%  GENERATED by tools/gen_sets.py -- do not edit.
%  Seed {seed}; regenerate with `make sets`.
% ======================================================

\\begin{{zestaw}}{{{title}}}{{{stars}}}{{{target}}}{{{cols}}}
{body}\\end{{zestaw}}
"""


def fmt(n: int) -> str:
    """Polish thousands separator: a thin space, never a comma."""
    s = f"{n:,}".replace(",", r"\,")
    return s


def dodawanie(r, n, lo, hi):
    for _ in range(n):
        a, b = r.randint(lo, hi), r.randint(lo, hi)
        yield f"${fmt(a)} + {fmt(b)}$", fmt(a + b)


def odejmowanie(r, n, lo, hi):
    for _ in range(n):
        a, b = r.randint(lo, hi), r.randint(lo, hi)
        if b > a:
            a, b = b, a
        yield f"${fmt(a)} - {fmt(b)}$", fmt(a - b)


def mnozenie(r, n, alo, ahi, blo, bhi):
    for _ in range(n):
        a, b = r.randint(alo, ahi), r.randint(blo, bhi)
        yield rf"${fmt(a)} \times {fmt(b)}$", fmt(a * b)


def dzielenie(r, n, blo, bhi, qlo, qhi):
    """Built from the quotient outwards, so every division comes out exact."""
    for _ in range(n):
        b, q = r.randint(blo, bhi), r.randint(qlo, qhi)
        yield rf"${fmt(b * q)} \div {fmt(b)}$", fmt(q)


def kolejnosc(r, n):
    """Order of operations: the answer differs if you go left to right."""
    for _ in range(n):
        shape = r.randint(0, 3)
        a, b, c = r.randint(2, 12), r.randint(2, 12), r.randint(2, 20)
        if shape == 0:
            yield rf"${c} + {a} \times {b}$", fmt(c + a * b)
        elif shape == 1:
            yield rf"${c * a + b} - {a} \times {b // 2 + 1}$", fmt(c * a + b - a * (b // 2 + 1))
        elif shape == 2:
            yield rf"$({a} + {b}) \times {c % 8 + 2}$", fmt((a + b) * (c % 8 + 2))
        else:
            q = r.randint(2, 9)
            yield rf"${a * q} \div {q} + {b}$", fmt(a + b)


def procenty(r, n):
    for _ in range(n):
        p = r.choice([5, 10, 20, 25, 50])
        base = r.choice([40, 60, 80, 120, 140, 160, 200, 240, 300, 400])
        yield rf"${p}\%$ z ${fmt(base)}$", fmt(base * p // 100)


def kwadraty(r, n):
    for _ in range(n):
        a = r.randint(11, 40)
        yield f"${a}^2$", fmt(a * a)


SETS = [
    # (filename, title, stars, target, columns, seed, builder)
    ("01-dodawanie-2c", "Dodawanie dwucyfrowe", 1, "2:30", 3, 1001,
     lambda r: list(dodawanie(r, 30, 11, 99))),
    ("02-odejmowanie-2c", "Odejmowanie dwucyfrowe", 1, "2:30", 3, 1002,
     lambda r: list(odejmowanie(r, 30, 11, 99))),
    ("03-mnozenie-tabliczka", "Tabliczka mnożenia", 1, "2:00", 3, 1003,
     lambda r: list(mnozenie(r, 30, 2, 9, 2, 9))),
    ("04-dzielenie-tabliczka", "Dzielenie w tabliczce", 1, "2:30", 3, 1004,
     lambda r: list(dzielenie(r, 30, 2, 9, 2, 9))),
    ("05-dodawanie-3c", "Dodawanie trzycyfrowe", 2, "4:00", 3, 1005,
     lambda r: list(dodawanie(r, 30, 101, 899))),
    ("06-odejmowanie-3c", "Odejmowanie trzycyfrowe", 2, "4:00", 3, 1006,
     lambda r: list(odejmowanie(r, 30, 101, 899))),
    ("07-mnozenie-2x1", "Mnożenie dwucyfrowe przez jednocyfrowe", 2, "4:00", 3, 1007,
     lambda r: list(mnozenie(r, 30, 12, 99, 3, 9))),
    ("08-dzielenie-3c", "Dzielenie trzycyfrowe", 2, "4:30", 3, 1008,
     lambda r: list(dzielenie(r, 30, 3, 12, 11, 40))),
    ("09-kolejnosc", "Kolejność działań", 2, "5:00", 2, 1009,
     lambda r: list(kolejnosc(r, 24))),
    ("10-procenty", "Procenty w pamięci", 2, "4:00", 3, 1010,
     lambda r: list(procenty(r, 30))),
    ("11-kwadraty", "Kwadraty", 3, "5:00", 3, 1011,
     lambda r: list(kwadraty(r, 30))),
    ("12-mnozenie-2x2", "Mnożenie dwucyfrowe", 3, "6:00", 3, 1012,
     lambda r: list(mnozenie(r, 24, 12, 49, 12, 49))),
    ("13-mieszane-szybkie", "Mieszane — szybkie", 2, "4:30", 3, 1013,
     lambda r: (list(dodawanie(r, 8, 11, 99)) + list(odejmowanie(r, 8, 11, 99))
                + list(mnozenie(r, 7, 3, 12, 3, 9)) + list(dzielenie(r, 7, 2, 9, 3, 12)))),
    ("14-mieszane-dluzsze", "Mieszane — dłuższe", 3, "7:00", 2, 1014,
     lambda r: (list(dodawanie(r, 6, 101, 999)) + list(odejmowanie(r, 6, 101, 999))
                + list(kolejnosc(r, 6)) + list(procenty(r, 6)))),
]


def render(name, title, stars, target, cols, seed, build) -> str:
    r = random.Random(seed)
    items = build(r)
    body = "".join(f"  \\z{{{q}}}{{{a}}}\n" for q, a in items)
    return HEADER.format(seed=seed, title=title, stars=stars,
                         target=target, cols=cols, body=body)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true")
    a = p.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    stale, total = [], 0
    for name, title, stars, target, cols, seed, build in SETS:
        text = render(name, title, stars, target, cols, seed, build)
        total += text.count("\\z{")
        dest = OUT / f"{name}.tex"
        cur = dest.read_text(encoding="utf8") if dest.exists() else None
        if cur == text:
            continue
        if a.check:
            stale.append(dest.relative_to(ROOT))
        else:
            dest.write_text(text, encoding="utf8")

    # The include list is generated too: a set added to SETS and forgotten in
    # structure.tex is a set nobody ever sees, and every other check passes.
    inc = ("% GENERATED by tools/gen_sets.py -- do not edit.\n"
           + "".join(f"\\input{{sets/generated/{n}}}\n" for n, *_ in SETS))
    incdest = OUT / "_all.tex"
    cur = incdest.read_text(encoding="utf8") if incdest.exists() else None
    if cur != inc:
        if a.check:
            stale.append(incdest.relative_to(ROOT))
        else:
            incdest.write_text(inc, encoding="utf8")

    if stale:
        for s in stale:
            print(f"  STALE   {s}")
        print(f"\n{len(stale)} generated file(s) out of date. Run `make sets`.")
        return 1
    print(f"  {len(SETS)} generated sets, {total} exercises")
    return 0


if __name__ == "__main__":
    sys.exit(main())
