#!/usr/bin/env python3
"""Generate the book's drill sets.

WHY GENERATED. This book is scored on how many exercises you get through and
how fast, so it needs hundreds of them, and hundreds of hand-written sums is
both a waste of a person and a place for arithmetic slips to hide. Everything
here is produced and its answer computed by the same three lines, so a printed
answer cannot disagree with its printed question.

DETERMINISTIC. Every set seeds its own Random with a fixed integer, so the book
is byte-identical on every machine and every run. A drill book whose pages
change under you cannot be re-run to compare times, which is the one thing this
book is for.

    tools/gen_sets.py            # write book/sets/generated/
    tools/gen_sets.py --check    # fail if the tree is stale

Hand-written sets -- logic, sequences, tricks -- live in book/sets/ and are not
touched by this script. Those cannot be generated: a word trap is a joke, and a
joke has an author.
"""
from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "book" / "sets" / "generated"

# The set length, in one place. It is a property of the FORMAT, not of any one
# set: a reader who has timed set 3 against set 11 is comparing two numbers that
# only mean something if the sets are the same length. Mixed sets divide it with
# split() rather than naming their own counts, so changing this one integer
# moves every set together and none of them drifts out of step.
N = 40

HEADER = """\
% ======================================================
%  GENERATED by tools/gen_sets.py -- do not edit.
%  Seed {seed}; regenerate with `make sets`.
% ======================================================

\\begin{{zestaw}}{{{title}}}{{{stars}}}{{{target}}}{{{cols}}}
{body}\\end{{zestaw}}
"""


def fmt(n: int) -> str:
    """Polish thousands separator: a thin space, never a comma."""
    s = f"{n:,}".replace(",", r"\,")
    return s


def dec(tenths: int) -> str:
    """Tenths as a decimal for MATH mode. `{,}` because a bare comma in math is
    punctuation and TeX puts a space after it -- `1,5` would set as `1, 5`."""
    return f"{tenths // 10}{{,}}{tenths % 10}"


def dect(tenths: int) -> str:
    """The same number for TEXT mode, where a comma is just a comma. The answer
    appendix is text, so the two forms are not interchangeable."""
    return f"{tenths // 10},{tenths % 10}"


def split(n: int, k: int) -> list[int]:
    """k counts summing to n, so a mixed set is exactly N long whatever N is."""
    base, rest = divmod(n, k)
    return [base + (1 if i < rest else 0) for i in range(k)]


def distinct(n, draw, seen=None):
    """n exercises, no two of them the same.

    Every builder below draws at random, and a set is now long enough that by
    the birthday problem it repeats almost every time: forty draws from the
    sixty-four multiplication-table pairs collide on about nine of them. A
    repeat inside one timed set reads as a printing error, and it measures
    nothing the first copy did not already measure.

    The attempt bound is what makes a builder whose space is smaller than n
    fail here, loudly, instead of spinning forever in a build that never ends.
    """
    seen = set() if seen is None else seen
    out, tries = [], 0
    while len(out) < n:
        tries += 1
        if tries > 200 * n:
            raise SystemExit(
                f"gen_sets: {draw.__name__} cannot produce {n} distinct "
                f"exercises -- widen its range or shorten the set")
        q, ans = draw()
        if q in seen:
            continue
        seen.add(q)
        out.append((q, ans))
    return out


# ------------------------------------------------------------------
#  Builders. Each DRAWS ONE exercise and computes its answer from the same
#  values it printed -- there is no second path a typo could take. distinct()
#  above turns a draw into a set.
#
#  NOTE ON NOTATION. Nothing here emits \sqrt or \frac. Both are taller than the
#  \strut that sets the row pitch in \z, so a set built from them breathes at a
#  different rate than every other set, and a reader running down a column with
#  a pencil feels it. Where the operation needs saying, it is said in words.
# ------------------------------------------------------------------

def dodawanie(r, lo, hi):
    a, b = r.randint(lo, hi), r.randint(lo, hi)
    return f"${fmt(a)} + {fmt(b)}$", fmt(a + b)


def odejmowanie(r, lo, hi):
    a, b = r.randint(lo, hi), r.randint(lo, hi)
    if b > a:
        a, b = b, a
    return f"${fmt(a)} - {fmt(b)}$", fmt(a - b)


def mnozenie(r, alo, ahi, blo, bhi):
    a, b = r.randint(alo, ahi), r.randint(blo, bhi)
    return rf"${fmt(a)} \times {fmt(b)}$", fmt(a * b)


def dzielenie(r, blo, bhi, qlo, qhi):
    """Built from the quotient outwards, so every division comes out exact."""
    b, q = r.randint(blo, bhi), r.randint(qlo, qhi)
    return rf"${fmt(b * q)} \div {fmt(b)}$", fmt(q)


def trzy_skladniki(r):
    a, b, c = r.randint(11, 79), r.randint(11, 79), r.randint(11, 79)
    return f"${a} + {b} + {c}$", fmt(a + b + c)


def dopelnienia(r):
    """Take away from a round number. The shortcut is to complement every digit
    against 9 and the last one against 10, which is why the minuend is round."""
    base = r.choice([100, 100, 200, 500, 1000, 1000])
    a = r.randint(base // 10, base - base // 10)
    return f"${fmt(base)} - {fmt(a)}$", fmt(base - a)


def podwajanie(r):
    """Halving only ever gets an even number, so no answer needs a fraction."""
    if r.random() < 0.5:
        a = r.randint(23, 480)
        return f"podw\\'{{o}}j ${fmt(a)}$", fmt(2 * a)
    a = 2 * r.randint(23, 480)
    return f"po\\l{{}}owa z ${fmt(a)}$", fmt(a // 2)


def triki(r):
    """The four multiplications that have a shortcut worth owning: x11 (digits
    out, their sum in), x5 (half, then x10), x9 (x10 less one), x25 (quarter,
    then x100). x25 gets a multiple of four so the quarter stays whole."""
    k = r.choice([11, 11, 5, 5, 9, 25])
    a = 4 * r.randint(3, 40) if k == 25 else r.randint(12, 89)
    return rf"${fmt(a)} \times {k}$", fmt(a * k)


def dziesietne(r):
    """One decimal place, so lining up the point is the whole difficulty.

    Neither operand ever ends in a zero tenth: `15{,}0` is a whole number
    wearing a decimal's clothes, and a set that mixes the two forms is asking
    two different questions under one heading."""
    def operand():
        t = r.randint(11, 199)
        while t % 10 == 0:
            t = r.randint(11, 199)
        return t

    a, b = operand(), operand()
    if r.random() < 0.5:
        return f"${dec(a)} + {dec(b)}$", dect(a + b)
    if b > a:
        a, b = b, a
    return f"${dec(a)} - {dec(b)}$", dect(a - b)


def czesci(r):
    """A fraction of a number. The base is a multiple of the denominator, so
    the answer is always whole -- this drills the division, not the remainder."""
    num, den = r.choice([(1, 2), (1, 3), (1, 4), (1, 5),
                         (2, 3), (3, 4), (2, 5), (3, 5)])
    base = den * r.randint(4, 40)
    return f"${num}/{den}$ z ${fmt(base)}$", fmt(base * num // den)


def reszty(r):
    b = r.choice([3, 4, 5, 6, 7, 8, 9, 11])
    a = r.randint(20, 199)
    return rf"reszta z ${fmt(a)} \div {b}$", fmt(a % b)


def kolejnosc(r):
    """Order of operations: the answer differs if you go left to right."""
    shape = r.randint(0, 3)
    a, b, c = r.randint(2, 12), r.randint(2, 12), r.randint(2, 20)
    if shape == 0:
        return rf"${c} + {a} \times {b}$", fmt(c + a * b)
    if shape == 1:
        return (rf"${c * a + b} - {a} \times {b // 2 + 1}$",
                fmt(c * a + b - a * (b // 2 + 1)))
    if shape == 2:
        return rf"$({a} + {b}) \times {c % 8 + 2}$", fmt((a + b) * (c % 8 + 2))
    q = r.randint(2, 9)
    return rf"${a * q} \div {q} + {b}$", fmt(a + b)


def procenty(r):
    p = r.choice([5, 10, 20, 25, 50])
    base = r.choice([20, 40, 60, 80, 100, 120, 140, 160, 180,
                     200, 240, 260, 300, 320, 400])
    return rf"${p}\%$ z ${fmt(base)}$", fmt(base * p // 100)


def procenty_trudne(r):
    """Every base is a multiple of twenty and every rate a multiple of five, so
    the result is whole without the drill ever having to say so."""
    p = r.choice([15, 30, 35, 40, 60, 75, 80, 90])
    base = r.choice([20, 40, 60, 80, 120, 140, 160, 180,
                     200, 240, 260, 300, 320, 400])
    return rf"${p}\%$ z ${fmt(base)}$", fmt(base * p // 100)


# The two enumerable sets are SAMPLED, not drawn: their whole space is barely
# bigger than a set, so rejection would spend most of its draws on collisions.
# Sampling also means the reader meets each square exactly once.
def kwadraty(r, n):
    return [(f"${a}^2$", fmt(a * a)) for a in r.sample(range(11, 11 + n), n)]


def pierwiastki(r, n):
    """In words, not \\sqrt -- see the note above the builders."""
    return [(f"pierwiastek z ${fmt(a * a)}$", fmt(a))
            for a in r.sample(range(4, 4 + n), n)]


def mieszane(r, draws):
    """Several builders in one set of exactly N, distinct across the whole set
    and not merely within each part."""
    seen, out = set(), []
    for count, draw in zip(split(N, len(draws)), draws):
        out += distinct(count, draw, seen)
    return out


# ------------------------------------------------------------------
#  The sets, in the order the reader meets them.
#
#  The list IS the ladder: one star, then two, then three. Renaming or
#  reordering is free, but a SEED IS NOT -- it is what makes set 7 the same
#  forty exercises this month as last month, which is the only reason timing
#  yourself against it twice means anything. Give a new set a new seed and
#  never reuse or renumber an old one.
# ------------------------------------------------------------------
SETS = [
    # (filename, title, stars, target, columns, seed, builder)

    # -- one star: the warm-ups -------------------------------------
    ("01-dodawanie-2c", "Dodawanie dwucyfrowe", 1, "3:20", 3, 1001,
     lambda r: distinct(N, lambda: dodawanie(r, 11, 99))),
    ("02-odejmowanie-2c", "Odejmowanie dwucyfrowe", 1, "3:20", 3, 1002,
     lambda r: distinct(N, lambda: odejmowanie(r, 11, 99))),
    ("03-mnozenie-tabliczka", "Tabliczka mnożenia", 1, "2:40", 3, 1003,
     lambda r: distinct(N, lambda: mnozenie(r, 2, 9, 2, 9))),
    ("04-dzielenie-tabliczka", "Dzielenie w tabliczce", 1, "3:20", 3, 1004,
     lambda r: distinct(N, lambda: dzielenie(r, 2, 9, 2, 9))),
    ("05-dopelnienia", "Dopełnienia do okrągłych", 1, "3:00", 3, 1015,
     lambda r: distinct(N, lambda: dopelnienia(r))),
    ("06-podwajanie", "Podwajanie i połowienie", 1, "3:00", 2, 1016,
     lambda r: distinct(N, lambda: podwajanie(r))),

    # -- two stars: the working range -------------------------------
    ("07-dodawanie-3c", "Dodawanie trzycyfrowe", 2, "5:20", 3, 1005,
     lambda r: distinct(N, lambda: dodawanie(r, 101, 899))),
    ("08-odejmowanie-3c", "Odejmowanie trzycyfrowe", 2, "5:20", 3, 1006,
     lambda r: distinct(N, lambda: odejmowanie(r, 101, 899))),
    ("09-trzy-skladniki", "Trzy składniki", 2, "6:00", 3, 1017,
     lambda r: distinct(N, lambda: trzy_skladniki(r))),
    ("10-mnozenie-2x1", "Mnożenie dwucyfrowe przez jednocyfrowe", 2, "5:20", 3, 1007,
     lambda r: distinct(N, lambda: mnozenie(r, 12, 99, 3, 9))),
    ("11-dzielenie-3c", "Dzielenie trzycyfrowe", 2, "6:00", 3, 1008,
     lambda r: distinct(N, lambda: dzielenie(r, 3, 12, 11, 40))),
    ("12-triki-mnozenia", "Mnożenie na skróty", 2, "4:30", 3, 1018,
     lambda r: distinct(N, lambda: triki(r))),
    ("13-reszty", "Reszty z dzielenia", 2, "5:00", 2, 1020,
     lambda r: distinct(N, lambda: reszty(r))),
    ("14-pierwiastki", "Pierwiastki kwadratowe", 2, "4:00", 2, 1021,
     lambda r: pierwiastki(r, N)),
    ("15-procenty", "Procenty w pamięci", 2, "5:20", 3, 1010,
     lambda r: distinct(N, lambda: procenty(r))),
    ("16-czesci", "Części liczby", 2, "5:00", 3, 1019,
     lambda r: distinct(N, lambda: czesci(r))),
    ("17-dziesietne", "Ułamki dziesiętne", 2, "5:00", 3, 1022,
     lambda r: distinct(N, lambda: dziesietne(r))),
    ("18-kolejnosc", "Kolejność działań", 2, "8:20", 2, 1009,
     lambda r: distinct(N, lambda: kolejnosc(r))),
    ("19-mieszane-szybkie", "Mieszane — szybkie", 2, "6:00", 3, 1013,
     lambda r: mieszane(r, [
         lambda: dodawanie(r, 11, 99),
         lambda: odejmowanie(r, 11, 99),
         lambda: mnozenie(r, 3, 12, 3, 9),
         lambda: dzielenie(r, 2, 9, 3, 12),
     ])),

    # -- three stars: the long ones ---------------------------------
    ("20-kwadraty", "Kwadraty", 3, "6:40", 3, 1011,
     lambda r: kwadraty(r, N)),
    ("21-mnozenie-3x1", "Mnożenie trzycyfrowe przez jednocyfrowe", 3, "8:00", 3, 1023,
     lambda r: distinct(N, lambda: mnozenie(r, 102, 899, 3, 9))),
    ("22-mnozenie-2x2", "Mnożenie dwucyfrowe", 3, "10:00", 3, 1012,
     lambda r: distinct(N, lambda: mnozenie(r, 12, 49, 12, 49))),
    ("23-procenty-trudne", "Procenty — trudniejsze", 3, "6:30", 3, 1024,
     lambda r: distinct(N, lambda: procenty_trudne(r))),
    ("24-mieszane-dluzsze", "Mieszane — dłuższe", 3, "9:00", 2, 1014,
     lambda r: mieszane(r, [
         lambda: dodawanie(r, 101, 999),
         lambda: odejmowanie(r, 101, 999),
         lambda: kolejnosc(r),
         lambda: procenty(r),
     ])),
    ("25-mieszane-final", "Mieszane — finał", 3, "11:00", 2, 1025,
     lambda r: mieszane(r, [
         lambda: mnozenie(r, 12, 49, 12, 49),
         lambda: dzielenie(r, 3, 12, 11, 40),
         lambda: procenty_trudne(r),
         lambda: dziesietne(r),
         lambda: kolejnosc(r),
     ])),
]


def render(name, title, stars, target, cols, seed, build) -> str:
    r = random.Random(seed)
    items = build(r)

    # The column break is written here, not left to the typesetter. A set is
    # laid out as one unbreakable row of boxes so that it cannot be split from
    # its own scoring box (see book/preamble.tex), and that means something has
    # to say where each box ends. split() balances them: forty over three
    # columns is 14/13/13, not 14/14/12.
    body, at = "", 0
    for i, count in enumerate(split(len(items), cols)):
        if i:
            body += "  \\btnc\n"
        for q, a in items[at:at + count]:
            body += f"  \\z{{{q}}}{{{a}}}\n"
        at += count

    return HEADER.format(seed=seed, title=title, stars=stars,
                         target=target, cols=cols, body=body)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true")
    a = p.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    stale, total = [], 0
    for name, title, stars, target, cols, seed, build in SETS:
        text = render(name, title, stars, target, cols, seed, build)
        total += text.count("\\z{")
        dest = OUT / f"{name}.tex"
        cur = dest.read_text(encoding="utf8") if dest.exists() else None
        if cur == text:
            continue
        if a.check:
            stale.append(dest.relative_to(ROOT))
        else:
            dest.write_text(text, encoding="utf8")

    # The include list is generated too: a set added to SETS and forgotten in
    # structure.tex is a set nobody ever sees, and every other check passes.
    inc = ("% GENERATED by tools/gen_sets.py -- do not edit.\n"
           + "".join(f"\\input{{sets/generated/{n}}}\n" for n, *_ in SETS))
    incdest = OUT / "_all.tex"
    cur = incdest.read_text(encoding="utf8") if incdest.exists() else None
    if cur != inc:
        if a.check:
            stale.append(incdest.relative_to(ROOT))
        else:
            incdest.write_text(inc, encoding="utf8")

    # And the other direction. Renaming a set leaves the old file behind, and
    # nothing above would ever look at it again: it is not in _all.tex, so it
    # is not in the book, and it is not in SETS, so no check compares it. It
    # would sit in the tree looking like a set the book contains.
    keep = {f"{n}.tex" for n, *_ in SETS} | {"_all.tex"}
    for f in sorted(OUT.glob("*.tex")):
        if f.name in keep:
            continue
        if a.check:
            stale.append(f.relative_to(ROOT))
        else:
            f.unlink()

    if stale:
        for s in stale:
            print(f"  STALE   {s}")
        print(f"\n{len(stale)} generated file(s) out of date. Run `make sets`.")
        return 1
    print(f"  {len(SETS)} generated sets, {total} exercises")
    return 0


if __name__ == "__main__":
    sys.exit(main())
